[project]
name = "mcp-deck"
version = "0.1.0"
description = "A FastMCP + MySQL starter template"
requires-python = ">=3.10"
dependencies = [
    "fastmcp==2.12.4",
    "mysql-connector-python",
    "pandas",
    "sqlalchemy",
    "python-dotenv",
]

[tool.setuptools.packages.find]
where = ["src"]
